### ISSUE TITLE
Gem installation problem: health_graph requires health_graph (>= 0)

### ISSUE THREAD

**Issue by JigneshGohel-BoTreeConsulting** [kennyma/health_graph#12]
I am facing the mentioned error in the subject of this issue.More details can be found here.
http://stackoverflow.com/q/13171479/936494

Thanks,
Jignesh Gohel

**Comment by ikbenben** [comment]
I know this is an old issue but I'm experiencing the same issue trying to install health_plan using ruby 2.1.3

Any suggestions on how to address this?

**Comment by journalbits** [comment]
I've just run into the same problem as well

**Comment by dsjoerg** [comment]
I resolved it on my branch with https://github.com/dsjoerg/health_graph/commit/9f4bc38998cc7b557992d18e04a6347503665cc9

**Comment by andrewpbrett** [comment]
This should be fixed in master now! Going to close.
